SOURCES = MultiThreadChatServerSync.java MultiThreadChatClient.java encryptor.java 

compile:
	javac -g $(SOURCES)

runMultiThreadChatServerSync:
	java MultiThreadChatServerSync

clean:
	rm *.class



